[project]
name = "casper"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clingo>=5.7.1",
]

[project.scripts]
casper = "src.app:entrypoint"

[tool.setuptools]
packages = ["src"]

